version: '3'
services:
  app1:
    build: .
    image: app1_python3
    container_name: python3_app1  
    ports:
      - "8501:8501"
    entrypoint: bash -c "streamlit run ocr.py"
    # volumes:
    #   - .:/app
