version: '3'
services:
  app:
    build: .
    image: app_python3
    container_name: python3_app  
    ports:
      - "8501:8501"
    entrypoint: bash -c "streamlit run user.py"
    # volumes:
    #   - .:/app
